services:
  - type: web
    name: redmoon0x
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
    plan: free
    healthCheckPath: /health
